In [1]:
import tensorflow as tf
from tensorflow import keras

C:\Users\BastOS\anaconda3\envs\timeseries\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\BastOS\anaconda3\envs\timeseries\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\BastOS\anaconda3\envs\timeseries\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\BastOS\anaconda3\envs\timeseries\lib\site-pack

# Univariate CNN Models

In [2]:
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    
    for i in range(len(sequence)):
        end_ix = i + n_steps
        
        if end_ix > len(sequence)-1:
            break
        
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    
    return array(X), array(y)

In [3]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [4]:
# reshape data as 3D array
n_features = 1
X = X.reshape(X.shape[0], X.shape[1], n_features)

In [5]:
# define model
model = keras.models.Sequential([
    keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu", input_shape=(n_steps, n_features)),
    keras.layers.MaxPooling1D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.Dense(50, activation="relu"),
    keras.layers.Dense(1)
])

model.compile(optimizer="adam", loss="mse")

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [6]:
# fit the model
model.fit(X, y, epochs=2000, verbose=0)

In [7]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape(1, n_steps, n_features)
yhat = model.predict(x_input)
print(yhat)

[[101.43073]]


# Multivariate CNN Models

## Multiple Input Series

In [8]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

In [9]:
from numpy import hstack

# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape(len(in_seq1), 1)
in_seq2 = in_seq2.reshape(len(in_seq2), 1)
out_seq = out_seq.reshape(len(out_seq), 1)

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
dataset

array([[ 10,  15,  25],
       [ 20,  25,  45],
       [ 30,  35,  65],
       [ 40,  45,  85],
       [ 50,  55, 105],
       [ 60,  65, 125],
       [ 70,  75, 145],
       [ 80,  85, 165],
       [ 90,  95, 185]])

In [10]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    
    for i in range(len(sequences)):
        end_ix = i + n_steps
        
        if end_ix > len(sequences):
            break
        
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    
    return array(X), array(y)

In [11]:
# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [12]:
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]

In [13]:
# define model
model = keras.models.Sequential([
    keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu", input_shape=(n_steps, n_features)),
    keras.layers.MaxPooling1D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.Dense(50, activation="relu"),
    keras.layers.Dense(1)
])

model.compile(optimizer="adam", loss="mse")

In [14]:
# fit the model
model.fit(X, y, epochs=2000, verbose=0)

In [15]:
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape(1, n_steps, n_features)
yhat = model.predict(x_input)
print(yhat)

[[205.99742]]


### Multi-headed CNN Model

In [70]:
# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)

(7, 3, 2) (7,)


In [71]:
# one time series per head
n_features = 1

In [72]:
# separate input data
X1 = X[:, :, 0].reshape(X.shape[0], X.shape[1], n_features)
X2 = X[:, :, 1].reshape(X.shape[0], X.shape[1], n_features)

In [73]:
# first input model
visible1 = keras.Input(shape=(n_steps, n_features))
cnn1 = keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu")(visible1)
cnn1 = keras.layers.MaxPooling1D(pool_size=2)(cnn1)
cnn1 = keras.layers.Flatten()(cnn1)

In [74]:
# second input model
visible2 = keras.Input(shape=(n_steps, n_features))
cnn2 = keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu")(visible2)
cnn2 = keras.layers.MaxPooling1D(pool_size=2)(cnn2)
cnn2 = keras.layers.Flatten()(cnn2)

In [75]:
# merge input models
merge = keras.layers.concatenate([cnn1, cnn2])
dense = keras.layers.Dense(50, activation="relu")(merge)
output = keras.layers.Dense(1)(dense)

In [76]:
# connect input and output models
model = keras.models.Model(inputs=[visible1, visible2], outputs=output)
model.compile(optimizer="adam", loss="mse")

In [77]:
model.summary()

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_10 (InputLayer)           [(None, 3, 1)]       0                                            
__________________________________________________________________________________________________
input_11 (InputLayer)           [(None, 3, 1)]       0                                            
__________________________________________________________________________________________________
conv1d_8 (Conv1D)               (None, 2, 64)        192         input_10[0][0]                   
__________________________________________________________________________________________________
conv1d_9 (Conv1D)               (None, 2, 64)        192         input_11[0][0]                   
____________________________________________________________________________________________

In [80]:
# fit the model
model.fit([X1, X2], y, epochs=1000, verbose=0)

In [81]:
# reshape one sample for making a prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x1 = x_input[:, 0].reshape(1, n_steps, n_features)
x2 = x_input[:, 1].reshape(1, n_steps, n_features)
yhat = model.predict([x1, x2])
print(yhat)

[[206.15004]]


## Multiple Parallel Series

In [88]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    
    for i in range(len(sequences)):
        end_ix = i + n_steps
        
        if end_ix > len(sequences)-1:
            break
        
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
        X.append(seq_x)
        y.append(seq_y)
    
    return array(X), array(y)

In [95]:
# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)
n_features = X.shape[2]
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


In [96]:
# define model
model = keras.models.Sequential([
    keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu", input_shape=(n_steps, n_features)),
    keras.layers.MaxPooling1D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.Dense(50, activation="relu"),
    keras.layers.Dense(n_features)
])

model.compile(optimizer="adam", loss="mse")

In [100]:
# fit the model
model.fit(X, y, epochs=3000, verbose=0)

In [101]:
# demonstrate prediction
x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape(1, n_steps, n_features)
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[101.27457 106.5281  207.04974]]


### Multi-output CNN Model

In [102]:
# define model
visible = keras.Input(shape=(n_steps, n_features))
cnn = keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu")(visible)
cnn = keras.layers.MaxPooling1D(pool_size=2)(cnn)
cnn = keras.layers.Flatten()(cnn)
cnn = Dense(50, activation='relu')(cnn)

In [103]:
# define output 1
output1 = keras.layers.Dense(1)(cnn)

# define output 2
output2 = keras.layers.Dense(1)(cnn)

# define output 3
output3 = keras.layers.Dense(1)(cnn)

model = keras.models.Model(inputs=visible, outputs=[output1, output2, output3])
model.compile(optimizer="adam", loss="mse")

In [104]:
# reshape data
y1 = y[:, 0].reshape(y.shape[0], 1)
y2 = y[:, 1].reshape(y.shape[0], 1)
y3 = y[:, 1].reshape(y.shape[0], 1)

In [105]:
# fit model
model.fit(X, [y1, y2, y3], epochs=2000, verbose=0)

In [106]:
# demonstrate prediction
x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape(1, n_steps, n_features)
yhat = model.predict(x_input)
print(yhat)

[array([[101.24713]], dtype=float32), array([[106.86522]], dtype=float32), array([[107.04974]], dtype=float32)]


# Multi-step CNN Models

In [116]:
# split a univariate sequence into samples
def split_sequence(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    
    for i in range(len(sequences)):
        end_ix = i + n_steps_in
        end_out = end_ix + n_steps_out
        if end_out > len(sequences):
            break
        
        seq_x, seq_y = sequences[i:end_ix], sequences[end_ix:end_out]
        X.append(seq_x)
        y.append(seq_y)
    
    return array(X), array(y)

In [118]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(5, 3) (5, 2)
[10 20 30] [40 50]
[20 30 40] [50 60]
[30 40 50] [60 70]
[40 50 60] [70 80]
[50 60 70] [80 90]


In [119]:
# reshape data
n_features = 1
X = X.reshape(X.shape[0], n_steps_in, n_features)

In [120]:
# define model
model = keras.models.Sequential([
    keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu", input_shape=(n_steps, n_features)),
    keras.layers.MaxPooling1D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.Dense(50, activation="relu"),
    keras.layers.Dense(n_steps_out)
])

model.compile(optimizer="adam", loss="mse")

In [121]:
# fit model
model.fit(X, y, epochs=2000, verbose=0)

In [122]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape(1, n_steps, n_features)
yhat = model.predict(x_input)
print(yhat)

[[101.67432  112.048836]]


# Multivariate Multi-step CNN Models

### Multiple Input Multi-step Output

In [125]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    
    for i in range(len(sequences)):
        end_ix = i + n_steps_in
        end_out = end_ix + n_steps_out -1
        if end_out > len(sequences):
            break
        
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:end_out, -1]
        X.append(seq_x)
        y.append(seq_y)
    
    return array(X), array(y)

In [126]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# convert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 2) (6, 2)
[[10 15]
 [20 25]
 [30 35]] [65 85]
[[20 25]
 [30 35]
 [40 45]] [ 85 105]
[[30 35]
 [40 45]
 [50 55]] [105 125]
[[40 45]
 [50 55]
 [60 65]] [125 145]
[[50 55]
 [60 65]
 [70 75]] [145 165]
[[60 65]
 [70 75]
 [80 85]] [165 185]


In [128]:
n_features = X.shape[2]

In [129]:
# define model
model = keras.models.Sequential([
    keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu", input_shape=(n_steps, n_features)),
    keras.layers.MaxPooling1D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.Dense(50, activation="relu"),
    keras.layers.Dense(n_steps_out)
])

model.compile(optimizer="adam", loss="mse")

In [130]:
model.fit(X, y, epochs=2000, verbose=0)

In [131]:
# demonstrate prediction
x_input = array([[70, 75], [80, 85], [90, 95]])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[185.45909 207.07306]]


### Multiple Parallel Input and Multi-step Output

In [140]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    
    for i in range(len(sequences)):
        end_ix = i + n_steps_in
        end_out = end_ix + n_steps_out
        if end_out > len(sequences):
            break
        
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:end_out, :]
        X.append(seq_x)
        y.append(seq_y)
    
    return array(X), array(y)

In [150]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# convert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(5, 3, 3) (5, 2, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [[ 40  45  85]
 [ 50  55 105]]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [[ 50  55 105]
 [ 60  65 125]]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [[ 60  65 125]
 [ 70  75 145]]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [[ 70  75 145]
 [ 80  85 165]]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [[ 80  85 165]
 [ 90  95 185]]


In [151]:
n_features = X.shape[2]

In [152]:
# flatten output
n_out = y.shape[1] * y.shape[2]
y = y.reshape(y.shape[0], n_out)

In [153]:
# define model
model = keras.models.Sequential([
    keras.layers.Conv1D(filters=64, kernel_size=2, activation="relu", input_shape=(n_steps, n_features)),
    keras.layers.MaxPooling1D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.Dense(50, activation="relu"),
    keras.layers.Dense(n_out)
])

model.compile(optimizer="adam", loss="mse")

In [154]:
# fit model
model.fit(X, y, epochs=2000, verbose=0)

In [155]:
# demonstrate prediction
x_input = array([[60, 65, 125], [70, 75, 145], [80, 85, 165]])
x_input = x_input.reshape(1, n_steps_in, n_features)
yhat = model.predict(x_input)
print(yhat)

[[ 90.94595  96.92466 187.8338  102.62279 108.12973 210.96928]]
